version: '3.5'

services:
  web:
    image: flaskpy2
    ports:
      - "5002:5002"
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
    command: python main.py

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    ports:
      - "3306:3306"
    volumes:
        - data:/root/SSMS
        - ./sql:/root/SSMS/
    environment:
      MYSQL_ROOT_PASSWORD: 123

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  data:
    driver: local
